<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Implementation\ItemsService.cs" />
    <Compile Remove="Interface\IItems.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AspNetCore.HealthChecks.SqlServer" Version="6.0.1" />
    <PackageReference Include="Azure.Storage.Blobs" Version="12.13.0" />
    <PackageReference Include="Beginor.Owin.Security.Aes" Version="0.2.2" />
    <PackageReference Include="CorePush" Version="3.1.1" />
    <PackageReference Include="FastMember" Version="1.5.0" />
    <PackageReference Include="FirebaseAdmin" Version="2.3.0" />
    <PackageReference Include="Google.Apis.Calendar.v3" Version="1.55.0.2500" />
    <PackageReference Include="Google.Apis.Translate.v3" Version="1.57.0.2808" />
    <PackageReference Include="MailKit" Version="3.4.1" />
    <PackageReference Include="Microsoft.AspNetCore" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="5.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="5.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="5.0.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="3.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="5.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="5.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Caching.SqlServer" Version="5.0.0" />
    <PackageReference Include="Microsoft.FeatureManagement" Version="2.4.0" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="6.15.0" />
    <PackageReference Include="MimeKit" Version="3.4.1" />
    <PackageReference Include="NEST" Version="7.17.4" />
    <PackageReference Include="NETCore.MailKit" Version="2.0.3" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
    <PackageReference Include="OneSignalApi" Version="1.0.2" />
    <PackageReference Include="SendGrid" Version="9.28.1" />
    <PackageReference Include="Serilog.Extensions.Logging.File" Version="2.0.0" />
    <PackageReference Include="Serilog.Settings.Configuration" Version="3.3.0" />
    <PackageReference Include="Serilog.Sinks.MSSqlServer" Version="5.6.1" />
    <PackageReference Include="Serilog.Sinks.RollingFile" Version="3.3.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="6.15.0" />
    <PackageReference Include="System.Runtime.Extensions" Version="4.3.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DomainLayer\DomainLayer.csproj" />
    <ProjectReference Include="..\RepositoryLayer\RepositoryLayer.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="System.Device">
      <HintPath>..\..\..\..\..\..\..\..\..\Windows\System32\System.Device.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
